# Site settings
title: "Yeehaw"
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/creative-theme-jekyll/" # the subpath of your site, e.g. /blog/
url: "spectralvectors.github.io" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
